import React, { useState } from 'react';
import {
  Download, FileText, MessageSquare, Linkedin, HelpCircle,
  Star, TrendingUp, Target, Award, Eye, RefreshCw,
  CheckCircle, Briefcase, Building2, Calendar
} from 'lucide-react';
import toast from 'react-hot-toast';
import { apiService } from '../services/api';

const ResultsDisplay = ({ results, onStartOver, analysisType }) => {
  const [activeTab, setActiveTab] = useState('overview');
  const [generating, setGenerating] = useState(false);

  if (!results || !results.detailed_results) {
    return (
      <div className="text-center py-12">
        <div className="text-red-500 mb-4">
          <AlertCircle className="w-16 h-16 mx-auto" />
        </div>
        <h3 className="text-xl font-bold text-gray-900 mb-4">No Results Available</h3>
        <p className="text-gray-600 mb-6">Something went wrong during the analysis.</p>
        <button
          onClick={onStartOver}
          className="btn-primary px-6 py-3 bg-gradient-to-r from-indigo-500 to-cyan-500 text-white rounded-lg hover:shadow-lg transition-all"
        >
          Try Again
        </button>
      </div>
    );
  }

  const { detailed_results } = results;

  const handleDownload = async (fileType) => {
    try {
      if (!results?.analysis_id) {
        toast.error('No analysis ID found');
        return;
      }

      const response = await apiService.get(`/api/analysis/download/${results.analysis_id}/${fileType}`);
      
      // Create a new window/tab to display the content
      const newWindow = window.open('', '_blank');
      if (newWindow) {
        newWindow.document.write(`
          <html>
            <head>
              <title>${response.filename}</title>
              <style>
                body { 
                  font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; 
                  margin: 40px; 
                  line-height: 1.6; 
                  color: #333;
                }
                pre { 
                  background: #f8f9fa; 
                  padding: 20px; 
                  overflow-x: auto; 
                  border-radius: 8px;
                  border: 1px solid #e9ecef;
                }
                .json-content { 
                  white-space: pre-wrap; 
                  background: #f8f9fa;
                  padding: 20px;
                  border-radius: 8px;
                  border: 1px solid #e9ecef;
                }
                h1 { color: #2563eb; border-bottom: 2px solid #e9ecef; padding-bottom: 10px; }
                .header { background: #f8f9fa; padding: 20px; margin: -40px -40px 30px -40px; border-bottom: 1px solid #e9ecef; }
              </style>
            </head>
            <body>
              <div class="header">
                <h1>📄 ${response.file_type.replace('_', ' ').toUpperCase()}</h1>
                <p><strong>Generated by JobSasa</strong> • ${new Date().toLocaleDateString()}</p>
              </div>
              <div class="json-content">${fileType.endsWith('_analysis') || fileType.endsWith('_research') ? 
                JSON.stringify(JSON.parse(response.content), null, 2) : 
                response.content.replace(/\n/g, '<br/>').replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>')
              }</div>
              <br/>
              <p style="margin-top: 30px; padding-top: 20px; border-top: 1px solid #e9ecef;">
                <em style="color: #666;">${response.message}</em>
              </p>
            </body>
          </html>
        `);
        newWindow.document.close();
      }
      
      toast.success(`${fileType.replace('_', ' ')} opened successfully`);
      
    } catch (error) {
      console.error('Download error:', error);
      toast.error(`Failed to open ${fileType}: ${error.response?.data?.detail || error.message}`);
    }
  };

  const handleGenerateDocuments = async () => {
    try {
      setGenerating(true);
      toast.success('Generating professional documents...');
      
      const response = await apiService.post('/api/documents/generate', {
        analysis_id: results.analysis_id
      });
      
      if (response.status === 'success') {
        toast.success('Professional documents generated! Check download center.');
      } else {
        throw new Error(response.message || 'Generation failed');
      }
    } catch (error) {
      console.error('Document generation error:', error);
      toast.error(`Failed to generate documents: ${error.response?.data?.detail || error.message}`);
    } finally {
      setGenerating(false);
    }
  };

  const renderMatchScore = () => {
    const jobAnalysis = detailed_results.job_analysis;
    if (!jobAnalysis?.match_score) return null;

    const { match_score } = jobAnalysis;
    const overallScore = Math.round(match_score.overall_match || 0);
    const technicalScore = Math.round(match_score.technical_skills_match || 0);
    const experienceScore = Math.round(match_score.experience_match || 0);

    return (
      <div className="bg-gradient-to-r from-blue-50 to-indigo-50 border border-blue-200 rounded-2xl p-6 mb-6">
        <h3 className="text-xl font-bold text-blue-900 mb-6 flex items-center">
          <Target className="w-6 h-6 mr-2" />
          Job Match Analysis
        </h3>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
          <div className="text-center">
            <div className="relative w-20 h-20 mx-auto mb-3">
              <svg className="w-20 h-20 transform -rotate-90" viewBox="0 0 36 36">
                <path
                  d="M18 2.0845 a 15.9155 15.9155 0 0 1 0 31.831 a 15.9155 15.9155 0 0 1 0 -31.831"
                  fill="none"
                  stroke="#e2e8f0"
                  strokeWidth="3"
                />
                <path
                  d="M18 2.0845 a 15.9155 15.9155 0 0 1 0 31.831 a 15.9155 15.9155 0 0 1 0 -31.831"
                  fill="none"
                  stroke="#3b82f6"
                  strokeWidth="3"
                  strokeDasharray={`${overallScore}, 100`}
                />
              </svg>
              <div className="absolute inset-0 flex items-center justify-center">
                <span className="text-2xl font-bold text-blue-600">{overallScore}%</span>
              </div>
            </div>
            <div className="font-semibold text-blue-900">Overall Match</div>
          </div>

          <div className="text-center">
            <div className="metric-value text-2xl">{technicalScore}%</div>
            <div className="text-sm text-gray-600">Technical Skills</div>
            <div className="mt-2">
              <div className="w-full bg-gray-200 rounded-full h-2">
                <div 
                  className="bg-gradient-to-r from-green-400 to-green-600 h-2 rounded-full transition-all duration-500"
                  style={{ width: `${technicalScore}%` }}
                ></div>
              </div>
            </div>
          </div>

          <div className="text-center">
            <div className="metric-value text-2xl">{experienceScore}%</div>
            <div className="text-sm text-gray-600">Experience Match</div>
            <div className="mt-2">
              <div className="w-full bg-gray-200 rounded-full h-2">
                <div 
                  className="bg-gradient-to-r from-purple-400 to-purple-600 h-2 rounded-full transition-all duration-500"
                  style={{ width: `${experienceScore}%` }}
                ></div>
              </div>
            </div>
          </div>
        </div>
      </div>
    );
  };

  const renderJobSummary = () => (
    <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mb-6">
      <div className="card-hover p-6">
        <h4 className="font-semibold text-gray-900 mb-4 flex items-center">
          <Briefcase className="w-5 h-5 mr-2 text-blue-600" />
          Position Details
        </h4>
        <div className="space-y-3 text-sm">
          <div>
            <span className="font-medium text-gray-700">Company:</span>
            <span className="ml-2 text-gray-900">{results.company_name}</span>
          </div>
          <div>
            <span className="font-medium text-gray-700">Analysis Type:</span>
            <span className="ml-2 text-gray-900 capitalize">{analysisType}</span>
          </div>
          <div>
            <span className="font-medium text-gray-700">Date:</span>
            <span className="ml-2 text-gray-900">{new Date().toLocaleDateString()}</span>
          </div>
        </div>
      </div>

      <div className="card-hover p-6">
        <h4 className="font-semibold text-gray-900 mb-4 flex items-center">
          <CheckCircle className="w-5 h-5 mr-2 text-green-600" />
          Analysis Summary
        </h4>
        <ul className="text-sm text-gray-600 space-y-2">
          <li className="flex items-center">
            <CheckCircle className="w-4 h-4 mr-2 text-green-500" />
            Job requirements analyzed
          </li>
          <li className="flex items-center">
            <CheckCircle className="w-4 h-4 mr-2 text-green-500" />
            Resume optimized for ATS
          </li>
          {analysisType === 'extended' && (
            <>
              <li className="flex items-center">
                <CheckCircle className="w-4 h-4 mr-2 text-green-500" />
                Cover letter generated
              </li>
              <li className="flex items-center">
                <CheckCircle className="w-4 h-4 mr-2 text-green-500" />
                LinkedIn optimization completed
              </li>
              <li className="flex items-center">
                <CheckCircle className="w-4 h-4 mr-2 text-green-500" />
                Interview prep generated
              </li>
            </>
          )}
        </ul>
      </div>
    </div>
  );

  const renderTabContent = () => {
    switch (activeTab) {
      case 'overview':
        return (
          <div className="space-y-6">
            {renderMatchScore()}
            {renderJobSummary()}
            
            {/* Download Options */}
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
              {[
                { title: 'Optimized Resume', desc: 'ATS-friendly resume', icon: FileText, type: 'optimized_resume', color: 'blue' },
                { title: 'Final Report', desc: 'Complete analysis report', icon: Award, type: 'final_report', color: 'purple' },
                { title: 'Job Analysis', desc: 'Job requirements breakdown', icon: Briefcase, type: 'job_analysis', color: 'green' },
                ...(analysisType === 'extended' ? [
                  { title: 'Cover Letter', desc: 'Personalized cover letter', icon: MessageSquare, type: 'cover_letter', color: 'orange' },
                  { title: 'LinkedIn Guide', desc: 'Profile optimization', icon: Linkedin, type: 'linkedin_optimization', color: 'cyan' },
                  { title: 'Interview Prep', desc: 'Questions & guidance', icon: HelpCircle, type: 'interview_preparation', color: 'pink' }
                ] : [])
              ].map((item, idx) => (
                <div key={idx} className="card-hover p-6">
                  <div className={`w-12 h-12 rounded-lg mb-4 flex items-center justify-center ${
                    item.color === 'blue' ? 'bg-blue-100 text-blue-600' :
                    item.color === 'purple' ? 'bg-purple-100 text-purple-600' :
                    item.color === 'green' ? 'bg-green-100 text-green-600' :
                    item.color === 'orange' ? 'bg-orange-100 text-orange-600' :
                    item.color === 'cyan' ? 'bg-cyan-100 text-cyan-600' :
                    'bg-pink-100 text-pink-600'
                  }`}>
                    <item.icon className="w-6 h-6" />
                  </div>
                  <h4 className="font-semibold text-gray-900 mb-2">{item.title}</h4>
                  <p className="text-sm text-gray-600 mb-4">{item.desc}</p>
                  <button 
                    onClick={() => handleDownload(item.type)}
                    className="w-full text-sm bg-gradient-to-r from-indigo-500 to-cyan-500 text-white px-4 py-2 rounded-lg hover:shadow-lg transition-all"
                  >
                    <Eye className="w-4 h-4 inline mr-2" />
                    View Content
                  </button>
                </div>
              ))}
            </div>
          </div>
        );

      case 'documents':
        return (
          <div className="space-y-6">
            <div className="text-center">
              <h3 className="text-xl font-bold text-gray-900 mb-4">Professional Document Generation</h3>
              <p className="text-gray-600 mb-6">
                Generate professional DOCX and PDF versions of your optimized documents.
              </p>
              <button
                onClick={handleGenerateDocuments}
                disabled={generating}
                className="btn-primary px-8 py-3 bg-gradient-to-r from-indigo-500 to-cyan-500 text-white rounded-lg hover:shadow-lg transition-all disabled:opacity-50"
              >
                {generating ? (
                  <>
                    <RefreshCw className="w-5 h-5 inline mr-2 animate-spin" />
                    Generating...
                  </>
                ) : (
                  <>
                    <Download className="w-5 h-5 inline mr-2" />
                    Generate Professional Documents
                  </>
                )}
              </button>
            </div>
            
            <div className="bg-gradient-to-r from-amber-50 to-orange-50 border border-amber-200 rounded-lg p-6">
              <h4 className="font-semibold text-amber-800 mb-2">📄 Document Package Includes:</h4>
              <ul className="text-sm text-amber-700 space-y-1">
                <li>• Professional Resume (DOCX & PDF)</li>
                {analysisType === 'extended' && (
                  <>
                    <li>• Personalized Cover Letter (DOCX & PDF)</li>
                    <li>• LinkedIn Optimization Guide (DOCX & PDF)</li>
                    <li>• Interview Preparation Guide (DOCX & PDF)</li>
                  </>
                )}
                <li>• All documents are ATS-compliant and print-ready</li>
              </ul>
            </div>
          </div>
        );

      default:
        return null;
    }
  };

  return (
    <div className="space-y-6">
      {/* Success Header */}
      <div className="text-center mb-8">
        <div className="mx-auto w-16 h-16 bg-gradient-to-r from-green-400 to-green-600 rounded-full flex items-center justify-center mb-4">
          <CheckCircle className="w-8 h-8 text-white" />
        </div>
        <h2 className="text-3xl font-bold gradient-text mb-4">Analysis Complete! 🎉</h2>
        <p className="text-gray-600 max-w-2xl mx-auto">
          Your {analysisType === 'extended' ? 'comprehensive career package' : 'resume optimization'} is ready. 
          Review your results and download your optimized documents.
        </p>
      </div>

      {/* Tabs */}
      <div className="border-b border-gray-200 mb-6">
        <nav className="flex space-x-8">
          <button
            onClick={() => setActiveTab('overview')}
            className={`py-2 px-1 border-b-2 font-medium text-sm ${
              activeTab === 'overview'
                ? 'border-indigo-500 text-indigo-600'
                : 'border-transparent text-gray-500 hover:text-gray-700 hover:border-gray-300'
            }`}
          >
            📊 Overview & Results
          </button>
          <button
            onClick={() => setActiveTab('documents')}
            className={`py-2 px-1 border-b-2 font-medium text-sm ${
              activeTab === 'documents'
                ? 'border-indigo-500 text-indigo-600'
                : 'border-transparent text-gray-500 hover:text-gray-700 hover:border-gray-300'
            }`}
          >
            📄 Professional Documents
          </button>
        </nav>
      </div>

      {/* Tab Content */}
      {renderTabContent()}

      {/* Action Buttons */}
      <div className="flex flex-col sm:flex-row gap-4 justify-center pt-8 border-t border-gray-200">
        <button
          onClick={onStartOver}
          className="px-8 py-3 bg-gray-600 text-white rounded-lg hover:bg-gray-700 transition-colors"
        >
          Start New Analysis
        </button>
        <button
          onClick={() => setActiveTab('documents')}
          className="btn-secondary px-8 py-3 bg-gradient-to-r from-cyan-500 to-blue-500 text-white rounded-lg hover:shadow-lg transition-all"
        >
          Get Professional Documents
        </button>
      </div>

      {/* Success Message */}
      <div className="bg-gradient-to-r from-green-50 to-emerald-50 border border-green-200 rounded-lg p-4 text-center">
        <p className="text-green-800 text-sm">
          <strong>🎊 Phase 3 Complete!</strong> JobSasa now provides comprehensive career optimization with document generation! 
          <br />Your AI-powered career transformation is complete.
        </p>
      </div>
    </div>
  );
};

export default ResultsDisplay;